# Generated by Django 3.2 on 2024-03-06 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Username', models.CharField(default='', max_length=255)),
                ('Name', models.CharField(default='', max_length=255)),
                ('Specification', models.CharField(default='', max_length=255)),
                ('Password', models.CharField(default='', max_length=255)),
                ('Degree', models.CharField(default='', max_length=255)),
                ('Hospital', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Hospitals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hospital_Name', models.CharField(default='', max_length=255)),
                ('District', models.CharField(default='', max_length=255)),
                ('CityTown', models.CharField(default='', max_length=255)),
                ('Pincode', models.CharField(default='', max_length=255)),
                ('Address', models.CharField(default='', max_length=255)),
                ('Password', models.CharField(default='', max_length=255)),
                ('Available', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.IntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleep', models.DecimalField(blank=True, decimal_places=2, max_digits=5)),
                ('blood_low', models.IntegerField(null=True)),
                ('blood_high', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='profile/avator.png', upload_to='')),
                ('birth_date', models.DateField(default='None')),
                ('region', models.CharField(default='', max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('phonenumber', models.CharField(max_length=200, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('country', models.CharField(default='', max_length=255)),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('blood_type', models.CharField(max_length=3, null=True)),
                ('allergies', models.CharField(blank=True, max_length=255, null=True)),
                ('past_medical', models.CharField(max_length=255, null=True)),
                ('family_history', models.CharField(max_length=255, null=True)),
                ('medical_profile', models.BooleanField(default=False)),
                ('blood_low', models.IntegerField(null=True)),
                ('blood_high', models.IntegerField(null=True)),
                ('medications', models.CharField(max_length=255, null=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=200)),
                ('s2', models.CharField(max_length=200)),
                ('s3', models.CharField(max_length=200)),
                ('s4', models.CharField(max_length=200)),
                ('s5', models.CharField(max_length=200)),
                ('disease', models.CharField(max_length=200)),
                ('medicine', models.CharField(max_length=200)),
                ('medicine2', models.CharField(max_length=200, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.BooleanField(default=False)),
                ('blood_low', models.IntegerField(null=True)),
                ('blood_high', models.IntegerField(null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('bmi', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
