# Generated by Django 3.2 on 2024-03-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ment',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
