# Generated by Django 3.2 on 2024-03-06 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_ment_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weightrecord',
            name='sleep',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
