# Generated by Django 3.2 on 2024-03-06 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_ment_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ment',
            name='approved',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='doctor',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='medical',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='patient',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
