# Generated by Django 3.2 on 2024-03-07 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20240306_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ment',
            name='approved',
        ),
    ]
