# Generated by Django 3.2 on 2024-03-07 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_remove_ment_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='ment',
            name='hospital',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='doctor',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='medical',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='ment',
            name='patient',
            field=models.IntegerField(null=True),
        ),
    ]
