# Generated by Django 3.2 on 2024-03-07 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_ment_my_time_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ment',
            name='my_time_field',
            field=models.DateTimeField(null=True),
        ),
    ]
